### ISSUE TITLE
Aborting a placement with a force start causes side effects

### ISSUE THREAD

**Issue by mickmack1213** [RoboCup-SSL/ssl-game-controller#140]
Find a Sumatra Recording attached:

[2024-01-30_13-33-02.zip](https://github.com/RoboCup-SSL/ssl-game-controller/files/14097784/2024-01-30_13-33-02.zip)

What happens in the recording? Note both AIs are set to off.

1. The ball is placed manually inside the blue defense area.
2. After 5s a Keeper Held Ball Foul is issued
3. The ball placement is done manually by just placing the ball
4. After the successful ball placement the game is continued with a force start
5. The ball is placed back into the defense area
6. After 5s a Keeper Held Ball Foul is issued
7. Yet again ball placement, but this time the ball placement is interrupted with a manual force start
8. The ball is placed back into the defense area
9. Now it takes more than 20s for the Keeper Held Ball Foul to be issued.

Note the 30s ball placement timer is still counting down, although the ball placement was already aborted with the force start.

**Comment by mickmack1213** [comment]
After more detailed analysis: 

On step 4: the game is continued with a force start after the ball placement. The normal action would have been a Direct Free with a 5s timer. 

This timer also continues to run after the force start, and when the ball is placed inside the defense area to wait for the Keeper Held Ball 1.1s were still remaining on the Direct Free timer.

The Keeper Held Ball foul is then only issued after 6.1 s instead of the expected 5s.


It also correlates to what is seen with the placement timer. As soon as the placement timer ran down to 0s it takes 5s until the foul is issued.

**Comment by mickmack1213** [comment]
The problem can also be reproduced using the official GC UI and not only the Sumatra Refbox.

There has to be a STOP between the Direct Free and the Force Start. This stop also pauses the 5s Direct Free timer, so it might not be so uncommon for this to happen.

**Comment by g3force** [comment]
The `currentActionTimeRemaining` was not reset for commands like STOP or FORCE_START. The noProgressDetector waits for the timer to reach zero. That's why it took longer after a canceled ball placement. The remaining time of the ball placement had to pass, before the no-progress timer started to count.
