### ISSUE TITLE
Unit documentation in GameEvent

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboCup-SSL/ssl-game-controller#18]
Currently there's no documentation for a large part of the fields of what units they have for GameEvent, particularly the locations. Are these in meters? or millimiters (ssl-vision standard?)?

**Comment by g3force** [comment]
Oh, you are right... That documentation really is missing :/ All the protobuf files should be documented.
I tried to use SI units where ever possible. So it should be meters.
Except for the referee message, where the placement position is in mm for historical reasons.

**Comment by g3force** [comment]
I've updated the documentation

**Comment by g3force** [comment]
Do you think this is sufficient, or is there something that still really needs more documentation?

**Comment by rolfvdhulst** [comment]
Yes, this is more than sufficient! :+1: Thank you!
