### ISSUE TITLE
error occured in release binary at v3.0.0

### ISSUE THREAD

**Issue by nabeya11** [RoboCup-SSL/ssl-game-controller#78]
OS: Ubuntu20.04

The error is following 
``` bash
$ ./ssl-game-controller_v3.0.0_linux_amd64 
./ssl-game-controller_v3.0.0_linux_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./ssl-game-controller_v3.0.0_linux_amd64)
./ssl-game-controller_v3.0.0_linux_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./ssl-game-controller_v3.0.0_linux_amd64)
```

**Comment by g3force** [comment]
Thx for the hint. I've downgraded the build pipeline image to one that's still using Ubuntu 20.04, so the glibc version should be compatible again. Can you try version 3.1.0?

**Comment by nabeya11** [comment]
It works well, thanks.
And nice UI design! It seems to be flexible with the browser window size.


By the way, I now find options like "-address". It is convenient in that it allows me to open the UI from another PC.

**Comment by g3force** [comment]
great, thx for the feedback and I'm glad that you like the new UI design :)
